### ISSUE TITLE
1.01无法编译

### ISSUE THREAD

**Issue by jihongboo** [g763007297/ImageViewer#2]
/Pods/GQImageViewer/GQImageViewer/GQThirdPart/WebP.framework/Headers/types.h:20:10: 
Include of non-modular header inside framework module 'GQImageViewer.types'
麻烦作者看一下

**Comment by g763007297** [comment]
修改Xcode Build Settings的"allow non-modular includes in framework modules" 为yes就可以了

**Comment by jihongboo** [comment]
已解决，谢谢
