### ISSUE TITLE
关于pod 'GQImageViewer/WebP'的问题

### ISSUE THREAD

**Issue by Mr-lins** [g763007297/ImageViewer#3]
![snip20170515_1](https://cloud.githubusercontent.com/assets/26573094/26041650/25099e8c-3961-11e7-8aba-e977b571b579.png)
![snip20170515_2](https://cloud.githubusercontent.com/assets/26573094/26041675/5248b09a-3961-11e7-85a5-e8b68f2f0824.png)

这个是什么问题呢？

**Comment by g763007297** [comment]
podfile里面你只需要包含一条关于本库的pod
如果需要使用不支持webp的就只需要加pod 'GQImageViewer'
如果需要使用支持webp的就只需要加pod 'GQImageViewer/WebP'
希望能解决你的问题，非常感谢使用GQImageViewer。

**Comment by Mr-lins** [comment]
我重建一个功能 单独导入pod 'GQImageViewer/WebP'  也是不行哦。还是提示上面贴图那个。pod 'GQImageViewer' 这个就没问题。 
![snip20170515_4](https://cloud.githubusercontent.com/assets/26573094/26044474/21e776a0-3977-11e7-817e-fada9db0de7f.png)
![snip20170515_5](https://cloud.githubusercontent.com/assets/26573094/26044491/3fc26040-3977-11e7-8109-15703f294308.png)

**Comment by g763007297** [comment]
你是使用的本地pod源还是github上面的pod源？
使用pod search 'GQImageViewer' 查看一下历史版本记录，看是否和我的是同一个版本
![5fa7700e-868d-46d7-bd3e-3a705ea5e0df](https://cloud.githubusercontent.com/assets/8064030/26085061/dec0c1ae-3a13-11e7-8018-67d066a1a80b.png)
我看错误显示的是你的pod源里面没有我的支持webp的库索引，如果你使用的是github源请先使用pod repo update更新pod索引。

**Comment by Mr-lins** [comment]
恩恩  我更新本地仓库试一下
