### ISSUE TITLE
图片保存失败

### ISSUE THREAD

**Issue by jiulong80s** [g763007297/ImageViewer#4]
图片保存失败，原因未知，writeToFile errorcode = -4

替换保存方法后可以保存成功：
- (void)storeImageDataToDisk:(nullable NSData *)imageData forKey:(nullable NSString *)key {
    if (!imageData || !key) {
        return;
    }
    if (![_fileManager fileExistsAtPath:[self getImageFolder]]) {
        [_fileManager createDirectoryAtPath:[self getImageFolder] withIntermediateDirectories:YES attributes:nil error:NULL];
    }
    
        // get cache Path for image key
    NSString *imageFilePath = [self getPathByFileName:key];
        // transform to NSUrl
    NSURL *fileURL = [NSURL fileURLWithPath:imageFilePath];
    
    [_fileManager createFileAtPath:imageFilePath contents:imageData attributes:nil];
    
    [fileURL setResourceValue:@YES forKey:NSURLIsExcludedFromBackupKey error:nil];
}

**Comment by jiulong80s** [comment]
原始图片很大，超过2M。试过压缩图片保存，800多KB依旧writeToFile 失败

**Comment by g763007297** [comment]
多谢你提供的方法，已同步到最新代码中
