### ISSUE TITLE
图片下载前判断缓存有问题，没有判断读取缓存磁盘文件

### ISSUE THREAD

**Issue by jiulong80s** [g763007297/ImageViewer#5]
- (id<GQImageViwerOperationDelegate>)loadWithURL:(NSURL *)url progress:(GQImageViwerProgressBlock)progressBlock complete:(GQImageViwerCompleteBlock)completeBlock {
    __block UIImage *image = nil;
    if(![[GQImageCacheManager sharedManager] isImageInMemoryCacheWithUrl:url.absoluteString]){
。。。。。。

}

**Comment by g763007297** [comment]
考虑后期支持时时读取磁盘缓存

**Comment by g763007297** [comment]
版本1.1.0已支持设置缓存策略
