### ISSUE TITLE
的确不错，非常好用！

### ISSUE THREAD

**Issue by townetowne** [g763007297/ImageViewer#6]
有两点修改:
1.工程自带的图片下载器不太支持请求头,refer,agent之类
   直接换成了SDImageVIew的图片下载器
2.文字层用另外的控件实现，改写成一个漫画浏览器，组件对对内存控制很赞，之前用的组件内存问题改得头疼，推荐使用这个ImageViewer

**Comment by g763007297** [comment]
非常感谢你的肯定，对于上面两点修改我有做以下扩展：
1.自带图片下载器支持继承GQImageViewrBaseURLRequest自定义请求参数，并通过[[GQImageDataDownload sharedDownloadManager] setURLRequestClass:<#(__unsafe_unretained Class)#>]设置继承的请求类，下期考虑添加到configure里，不需要额外引用类。
2.这点需要开发者在底部视图中进行配置，也可以根据自己的业务进行修改，后期会考虑扩展性进行单独抽离。
