### ISSUE TITLE
图片浏览不能弹出

### ISSUE THREAD

**Issue by zejun-huang** [g763007297/ImageViewer#7]
我按照您的例子写了一个新的  在tableview上点击  cell 加载网络图片  但是只有一个能弹出View  其余的不能弹出View  不知道问题出在哪里？

**Comment by g763007297** [comment]
是直接使用的我这个还是你自己写的？

**Comment by zejun-huang** [comment]
是直接使用的你的，  比如我点击cell的时候   每个cell里面包含一个URL数组 这时候  可能只有某一个 cell可以点击进去   其余的则直接打印dissMiss。就如你的demo里面那样  ，我不知道为什么直接打印了dissMiss

**Comment by g763007297** [comment]
因为我这个是一个单例，会记录弹出状态，当你弹出一个之后你就要负责把当前弹出的dissMiss掉才能弹出下一个。

**Comment by zejun-huang** [comment]
哦哦  是需要自己手动dissMiss是吧

**Comment by zejun-huang** [comment]
您好 ，还有一个问题  就是当我点击cell的时候  直接调用下面  其实这个时候还未显示，请问怎么办

.dissMissChain(^(){
//
        NSLog(@"dissMiss");
    })

**Comment by zejun-huang** [comment]
还是那个问题 ，您好  ，我的列表有一写图片数组  ，点击cell有的能弹出View 有的不能  ，这是个什么情况呢？虽然是单例模式  但是  有的cell点击可以进去  有的却不行  ，不行的直接打印了dissMiss  ，能进去的 当我 下滑图片时  它也自己dissMiss  所以应该不用  手动管理  dissMiss了吧

**Comment by zejun-huang** [comment]
而且 cell里面 包含几张图片  他就dissMiss 几次  ，这也很奇怪 的一点

**Comment by g763007297** [comment]
如果你使用我里面的点击、滑动消失手势那就不需要自己dissmisss，但是如果你是自己让图片浏览器消失那就需要在下一次点击的时候主动调用dissmiss然后才能弹出来。
比如说你用一个view承载我的图片浏览器，然后你在remove你自己管理的view时就需要主动调用一次dissmiss方法让图片浏览器先重置弹出状态。

**Comment by zejun-huang** [comment]
+ (void)showImageViewAtInex:(NSInteger)index imagesURLs:(NSArray *)imageArray remarksArray:(NSArray *)textArray {
    ////    [GQImageViewer sharedInstance]
    //基本调用
    [[GQImageViewer sharedInstance] setImageArray:imageArray textArray:textArray];//这是数据源
    [GQImageViewer sharedInstance].selectIndex = index;//设置选中的索引
    [GQImageViewer sharedInstance].achieveSelectIndex = ^(NSInteger selectIndex){//获取当前选中的图片索引
        NSLog(@"%ld",selectIndex);
    };
    [GQImageViewer sharedInstance].configure = ^(GQImageViewrConfigure *configure) {//设置配置信息
        [configure configureWithImageViewBgColor:[UIColor blackColor]
                                 textViewBgColor:nil
                                       textColor:[UIColor whiteColor]
                                        textFont:[UIFont systemFontOfSize:12]
                                   maxTextHeight:100
                                  textEdgeInsets:UIEdgeInsetsMake(5, 5, 5, 5)
                                       scaleType:GQImageViewerScaleTypeEqualWidth];
    };
    [GQImageViewer sharedInstance].topViewConfigureChain(^(UIView *configureView) {//配置顶部view
        configureView.height = 50;
        configureView.backgroundColor = [UIColor redColor];
    });
    [GQImageViewer sharedInstance].bottomViewConfigureChain(^(UIView *configureView) {//配置底部view
        configureView.height = 50;
        configureView.backgroundColor = [UIColor yellowColor];
    });
    [[GQImageViewer sharedInstance] showInView:ApplicationDelegate.window animation:YES];//显示GQImageViewer到指定view上
    
}
您好  上面的代码 就是我 按照 您的demo  改写的 一个 继承您的  图片浏览器View 的 一个 方法  也就只有一个方法  我没有自己写  remove的方法  点击手势  滑动消失  也没有  变化 。请教一下 ，本人新手  。很感谢  您 抽空回复我的疑问。

**Comment by g763007297** [comment]
你直接加我QQ吧 763007297
