### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by scyios** [g763007297/ImageViewer#8]
兄弟 你写的挺好的, 但是我建议你核心功能用 sdwebimage去做或者你可以外露一个属性让我们选择原生的 还是 sdwebimage渲染, 因为很多时候的需求都是 外面一个九宫格布局 点击布局才到你的框架,  外面的九宫格 图片请求和渲染 大多数都用sdwebimage完成了  到你这个框架的时候 你可以直接调取sdwebimage的缓存 这样性能和效率都会高一些

**Comment by g763007297** [comment]
多谢你的支持，后期考虑使用subspec去支持

**Comment by g763007297** [comment]
已支持
